name: OpAnvils
main: me.varmetek.opanvils.OpAnvilsPlugin
version: 1.0.1
description: A plugin which extends the abilities of anvils to allow players to create items with enchantments that have levels far further than before.
authors:
  - Varmetek
commands:
#  perms:
  opanvils:
    aliases: opa
permissions:
  opanvils.*:
    description: Gives full access to all the features of the plugin
    children:
      opanvils.use: true
      opanvils.bypass: true
      opanvils.enchantment.*: true
      opanvils.admin: true
  opanvils.admin:
    description: Gives access to edit the config through UI and command
  opanvils.use:
    description: Gives access to use the features of this plugin
  opanvils.enchantment.*:
    description: Gives access to combine all enchantments without limit
  opanvils.bypass:
    description: Allows on the ability to bypass server enchantment limits